### ISSUE TITLE
Rails 4

### ISSUE THREAD

**Issue by xjunior** [ericallam/font_assets#40]
It doesn't seem like this works on Rails 4, does it?

**Comment by frontandstart** [comment]
try test and say to us

**Comment by sanyam-j** [comment]
yeah it not working

**Comment by nruth** [comment]
in general, or on heroku?

**Comment by sanyam-j** [comment]
@nruth On heroku

**Comment by nruth** [comment]
I too thought it was broken, or heroku's stack (Cowboy stripping headers) but with some fighting I got it to work just now using heroku -> cloudfront -> user

```
gem 'bootstrap-sass', '~> 3.3.5'
gem 'sass-rails', '>= 3.2'
gem 'font-awesome-sass', '~> 4.3.0'
gem 'font_assets'

config.font_assets.origin = '*'
```


and each time I redeployed I changed my config.assets.version in production.rb to make sure caching wasn't getting in the way. Much easier to do that than use cloudfront expiry requests.

cloudfront behaviours set up to forward Origin, Access-Control-Request-Method and Access-Control-Request-Headers. I want to try removing the ones other than Origin, but just happy it loaded the fonts for now.

How I debugged:

- Load your site in chrome, check the developer tools' console for CORS errors, and the network tab  to see what URL it's hitting for your assets
- if your asset urls are not pointing to hashed urls you are loading the scss in the wrong order, e.g.  load font-awesome-sprockets before font-awesome, and the same for bootstrap-sprockets and bootstrap.
- if you have CORS errors in the browser console the headers are not reaching your browser. Debug with curl: try against cloudfront, and directly against your rails app. If the Access-Control headers are missing you have a problem, and the problem is in your rails app, or you are being served a cached response from before you fixed your rails app. Try changing config.assets.version so all your asset hashes change.

```
curl -I 'https://yourapp.herokuapp.com/assets/font-awesome/fontawesome-webfont-9e540a087924a6e64790149d735cac022640e4fa6bff6bd65f5e9f41529bf0b3.ttf' -s
```

```
curl -I 'https://l3kjlkjf.cloudfront.net/assets/font-awesome/fontawesome-webfont-9e540a087924a6e64790149d735cac022640e4fa6bff6bd65f5e9f41529bf0b3.ttf' -s
```

**Comment by mepster** [comment]
@nruth thanks for the super helpful comment & detailed description of how to debug.

On cloudfront I am _only_ forwarding Origin, seems to work. I am on rails 4.2.1.

BTW, notice that release 0.1.11 of this gem doesn't have the newer woff2 mime-type. There are a couple more commits after that release and one of them includes it.

You can include the gem in your Gemfile like this instead to get woff2:
gem 'font_assets', github: 'ericallam/font_assets', ref: '457dcfddc4318e83679e9a0935612924b7717085'

@ericallam how about a 0.1.12 release of font_assets with the latest commits so that woff2 is included by default? (Thanks for the gem!)

**Comment by dimroc** [comment]
Are any of you using nginx or passenger? See below:
http://stackoverflow.com/questions/25945419/how-do-i-configure-access-control-allow-origin-with-rails-and-nginx

**Comment by bsbodden** [comment]
Nope.
